### ISSUE TITLE
Capability problems on CPT Tickets

### ISSUE THREAD

**Issue by bokorir** [moderntribe/event-tickets#135]
Hi,

I’m working on a site where I need to sell tickets for a Custom Post Type (CPT).
I set up the plugin but it’s not saving the tickets because of a php error.

I’m getting an error about:

> Notice: Undefined offset: 0 in /srv/www/domain.com/current/web/wp/wp-includes/capabilities.php on line 115

This happens because `Tribe__Tickets__Tickets->has_permission( )` is checking the capability in a bad way. (I guess)

```
    $cap = "edit_{$post->post_type}";
    if ( 'post' === $post->post_type || 'page' === $post->post_type ) {
        $cap .= 's';
    }
```

So my post type has registered with a singular name `course` (how it should be by default) and you check the `edit_{$post->post_type}` which is `edit_course` in this case. But to check this permission (`edit_post => edit_course`) you have to add another argument which is the post id.

[http://wordpress.stackexchange.com/a/84205/81135](http://wordpress.stackexchange.com/a/84205/81135)

I would suggest to check the capability based on the post type object.

**Comment by barryhughes** [comment]
Thank you for submitting the PR - we'll check that out as soon as we can :+1: 

Please also note that we are not actively monitoring the issue tracker at this time and it is therefore best to approach us on one of our support channels if you wish to report or discuss bugs and new features.

[Premium support forum](https://theeventscalendar.com/support/forums/) | [Open support forum](https://wordpress.org/plugins/event-tickets/) | [UserVoice](https://tribe.uservoice.com/forums/195723-feature-ideas)
