### ISSUE TITLE
Event Price using Events (free) + RSVP (free) 

### ISSUE THREAD

**Issue by SytzeW** [moderntribe/event-tickets#89]
I made an Event, let's say it is an Workshop. 
It has a price, say eur 25
Using Event Tickets (free) in Avada theme

Using Event Tickets (free) shows in the event that it is for free. 
I rather have NO price, as it is also in my Woo commerce shop.

**Comment by masteradhoc** [comment]
May you post your Support Request here: https://wordpress.org/support/plugin/event-tickets or https://theeventscalendar.com/support/forums/forum/event-tickets/event-tickets-plus/
With Event Tickets free it is just possible to create RSVP Events which you cant set a price... Buy Events Tickets Pro and you will be able to create Price and sell through different Stores (see https://theeventscalendar.com/product/wordpress-event-tickets-plus/)

**Comment by barryhughes** [comment]
Please note that we are not actively monitoring the issue tracker at this time and it is therefore best to approach us on one of our support channels if you wish to report or discuss bugs and new features.

[Premium support forum](https://theeventscalendar.com/support/forums/) | [Open support forum](https://wordpress.org/plugins/event-tickets/) | [UserVoice](https://tribe.uservoice.com/forums/195723-feature-ideas)
