### ISSUE TITLE
RSVP in Sidebar with too little space - no possibility to change with Fusion Builder

### ISSUE THREAD

**Issue by SytzeW** [moderntribe/event-tickets#90]
using Events (free) + RSVP (free) 
using Avada theme

Created an Event. 
Clicking on the Event shows description.
In de right (the sidebar?) a long column is showed containing location etc;
and also RSVP. 
Already the column is small and within this space left is number of tickets , and on the right is space of 10 characters for description. 
In this space the logo -that is also sent thru email- is shown above this little text and gets deformed, or only partially visible.

The extra description in RSVP that is for info only is also displayed in the Admin section for each attendee. This should be removed. 

There is no way to change the location of all these Fusion "builder blocks" to some other location. 
There is no link to an Event page to look into CSS. 

This really should be changed!

**Comment by masteradhoc** [comment]
May you post your Support Request here: https://wordpress.org/support/plugin/event-tickets or https://theeventscalendar.com/support/forums/forum/event-tickets/event-tickets-plus/

**Comment by barryhughes** [comment]
Please note that we are not actively monitoring the issue tracker at this time and it is therefore best to approach us on one of our support channels (as @masteradhoc suggested) if you wish to report or discuss bugs and new features.

[Premium support forum](https://theeventscalendar.com/support/forums/) | [Open support forum](https://wordpress.org/plugins/event-tickets/) | [UserVoice](https://tribe.uservoice.com/forums/195723-feature-ideas)
