### ISSUE TITLE
Email Marketing link using Events (free) + RSVP (free) ?

### ISSUE THREAD

**Issue by SytzeW** [moderntribe/event-tickets#91]
using Events (free) + RSVP (free) 
using Avada
using GetResponse fro email marketing

Once RSVP is submitted with name and email, the screen automatically goes to the URL mentioned in the Event for Product Info. But ...
Where can I find any integration with Forms? 
So how can I send emails to my registrars without having it to do all manually ?

Avada uses ContactForm7, I myself use GetResponse. 
The GetResponse plugin neatly integrates with CF7.

**Comment by masteradhoc** [comment]
May you post your Support Request here: https://wordpress.org/support/plugin/event-tickets or https://theeventscalendar.com/support/forums/forum/event-tickets/event-tickets-plus/

**Comment by barryhughes** [comment]
Please note that we are not actively monitoring the issue tracker at this time and it is therefore best to approach us on one of our support channels if you wish to report or discuss bugs and new features.

[Premium support forum](https://theeventscalendar.com/support/forums/) | [Open support forum](https://wordpress.org/plugins/event-tickets/) | [UserVoice](https://tribe.uservoice.com/forums/195723-feature-ideas)
